accounts/urls.py
from unicodedata import name
from django.urls import path
from accounts.views import AccountsLoginView, AccountsLogoutView, signup

urlpatterns = [
    path("login/", AccountsLoginView.as_view(), name="login"),
    path("logout/", AccountsLogoutView.as_view(), name="logout"),
    path("signup/", signup, name="sign_up"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountReceiptCreateView,
    CategoryCreateView,
    AccountListView,
    ExpenseCategoryListView
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path(
        "accounts/create/",
        AccountReceiptCreateView.as_view(),
        name="account_create",
    ),
    path(
        "catergories/create/",
        CategoryCreateView.as_view(),
        name="category_create",
    ),
    path("accounts/", AccountListView.as_view(), name="accounts_list"),
    path("categories/", ExpenseCategoryListView.as_view(), name="categories_list")
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from multiprocessing.sharedctypes import Value
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.models import User


# Create your views here.
class AccountsLoginView(LoginView):
    template_name = "registration/login.html"


class AccountsLogoutView(LogoutView):
    template_name = "registration/logged_out.html"


def signup(request):
    if request == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(
                username, email=None, password=None
            )
            user.save()
            login(request, user)
            return redirect(
                "home",
            )
    else:
        form = UserCreationForm(request.POST)
    # context = dictionary with key "form" and value form
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from urllib import request
from django.shortcuts import redirect, render
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from receipts.models import Account, ExpenseCategory, Receipt

# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/receipt_create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class AccountReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/account_create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/category_create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/catergory_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Receipts</title>
</head>
<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'home' %}">Receipts</a>
        </li>
        <li>
          <a href="{% url 'receipt_create' %}">Create receipt</a>
        </li>
        <li>
          <a href="{% url 'accounts_list' %}">Accounts</a>
        </li>
        <li>
          <a href="{% url 'account_create' %}">Create Account</a>
        </li>
        <li>
          <a href="{% url 'categories_list' %}">Catergories</a>
        </li>
        <li>
          <a href="{% url 'category_create' %}">Create category</a>
        </li>
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'login' %}">login</a>
        </li>
        <li>
          <a href="{% url 'sign_up' %}">signup</a>
        </li>
        {% endif %}
      </ul>
      </nav>
  </header>
  {% block content %}
  {% endblock content %}
</body>
</html>

receipts/templates/receipts/account_create.html
{% extends 'base.html' %}
{% block content %}
<h2>Create Account</h2
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button>Create</button>
    </div>
</form>
{% endblock content%}

receipts/templates/receipts/accounts_list.html
{% extends 'base.html' %}
{% block content %}
{% endblock content %}

receipts/templates/receipts/category_create.html
{% extends 'base.html' %}
{% block content %}
<h2>Create Catergory</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button>Create</button>
    </div>
</form>
{% endblock content %}

receipts/templates/receipts/category_list.html
{% extends 'base.html' %}
{% block content %}
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
<h1>Home</h1>
<table>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Catergory</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for receipt in receipt_list %}
        <tr>
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.table }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date }}</td>
            <td>{{ receipt.category }}</td>
            <td>{{ receipt.account.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
{% endblock content %}

receipts/templates/receipts/receipt_create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <h2>Create Receipt</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Create</button>
      </div>
    </form>
</main>
{% endblock content %}